# NumPy
 **NumPy is a Python library used for fast and efficient numerical computations with large datasets. It provides support for multi-dimensional arrays and offers functions for mathematical operations, making it essential for data analysis, machine learning, and scientific computing in data science.**

In [ ]:
import numpy as np
import numpy

In [ ]:
x=np.array([1,2,3])
print(x)


[1 2 3]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [ ]:
b2=np.array([[1,2,3],[4,5,6]])
x=np.array([1,2,3])
b2,x


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3]))

In [ ]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
b=np.array([[1.1,2.2,3.5],[4.2,5.3,6.4]])
print(b)

[[1.1 2.2 3.5]
 [4.2 5.3 6.4]]


In [ ]:
x=np.array([1,2,3])
y=np.array([1,2,3])
print(x*y)

[1 4 9]


In [ ]:
#Get Dimension(axes)
x.ndim

1

In [ ]:
b.ndim


2

In [ ]:
#Get Shape
print(x.shape)

# Printing size (total number of elements) of array
x.size

(3,)


3

In [ ]:
print(b.shape)

print(b.size)

(2, 3)
6


In [ ]:
#Get type
x.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
b1=np.array([[1,2,3],[4,5,6]])
print(b1.dtype)
b1

int32


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Creating array from list with type float
b1=np.array([[1,2,3],[4,5,6]],dtype='float')
print(b1.dtype)
b1

float64


array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
# Creating array from tuple
y1=np.array((1,3,2))
print("\nArray created using passed tuple:\n",y)
print(y1.dtype)
print(y1.shape)

print(y1.size)
y1


Array created using passed tuple:
 [1 2 3]
int32
(3,)
3


array([1, 3, 2])

In [ ]:
#Creating a 3-D array
arr=np.array([[[1,2,3], [4,5,6]], [[8,9,10], [4,5,6]]])
print(arr)
print(arr.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [ 4  5  6]]]
3


In [ ]:
arr1=np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(arr1)
print(arr1.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
arr2=np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

print(arr2.size)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4
(1, 1, 3, 3)
9


In [ ]:
arr3=np.array([1,2,3],ndmin=10)
print(arr3)
print(arr3.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [ ]:
#INITIALIZING DIFFERENT TYPES OF ARRAYS
#All 0s matrix i.e Array filled with O's
import numpy as np
az=np.zeros(4)
az

array([0., 0., 0., 0.])

In [ ]:
az1=np.zeros((2,3))
print(az1)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#All 1s matrix
a1=np.ones(4)
a1

array([1., 1., 1., 1.])

In [ ]:
a1=np.ones((4),dtype='int32')
print(a1)

[1 1 1 1]


In [ ]:
#empty array
ae=np.empty(4)
print(ae)

[1. 1. 1. 1.]


In [ ]:
ar_rn=np.arange(3)
print(ar_rn)


[0 1 2]


In [ ]:
#Creating an identity matrix ie diagonal element
ar_di=np.eye(3)
ar_di

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar_di=np.eye(3,5)
ar_di

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
ar_di=np.identity(3)
ar_di

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar_di=np.identity(5)
ar_di

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#linespace
ar_lin=np.linspace(0,5,5)  #start, stop, and num
ar_lin

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
#Any other number
z2=np.full((2,2),99)
print(z2)

[[99 99]
 [99 99]]


In [ ]:
np.full_like(ae,4)

array([4., 4., 4., 4.])

In [ ]:
#Random decimal numbers using rand() values would be in range of 0 to 1
var=np.random.rand(4)
var

array([0.34663778, 0.49555288, 0.45898534, 0.98528205])

In [ ]:
var=np.random.rand(4,2)
var

array([[0.8482369 , 0.64756931],
       [0.05158717, 0.66389716],
       [0.81715713, 0.10385025],
       [0.29264394, 0.54330611]])

In [ ]:
#Random integer values by specifying a given range eg:7
np.random.randint(7,size=(3,3))

array([[3, 1, 3],
       [3, 4, 4],
       [6, 1, 4]])

In [ ]:
#Random integer values by specifying a range eg -1,15
np.random.randint(-1,15,size=(2,2,3))

array([[[11, 14,  5],
        [ 5, 10,  8]],

       [[12,  0,  6],
        [-1,  5, 11]]])

In [ ]:
np.random.randint(-1,10,5)

array([-1, -1,  0,  4,  8])

In [ ]:
#randn() may return positive or negative numbers as well
var=np.random.randn(4,2)
var

array([[ 0.40822868, -0.29487849],
       [ 0.05678148,  0.00944403],
       [-0.1616103 , -0.33035289],
       [-1.00078035,  1.22240752]])

In [ ]:
#ranf() in the half open interval [0.0, 1.0]
var3=np.random.ranf(4)
var3

array([0.96488757, 0.38307043, 0.1432481 , 0.2047709 ])

In [ ]:
#Random decimal numbers from an existing shape of an array
np.random.random_sample(ar_lin.shape)

array([0.3546019 , 0.58414577, 0.51341981, 0.56445753, 0.28744853])

In [ ]:
#data types
var=np.array([1,2,3,4])
var.dtype

dtype('int32')

In [ ]:
var=np.array([1.1,2.1,3.2,4.2])
var.dtype

dtype('float64')

In [ ]:
var=np.array(["a","b","c","d"])
var.dtype

dtype('<U1')

In [ ]:
var=np.array(["abc","b1","ca","dedwa"])
var.dtype

dtype('<U5')

In [ ]:
var=np.array([1,2,3,4], dtype=np.int8)
var.dtype

dtype('int8')

In [ ]:
var=np.array([1,2,3,4], dtype=np.float16)
var.dtype

dtype('float16')

In [ ]:
var=np.array([1,2,3,4], dtype="f")
var.dtype

dtype('float32')

In [ ]:
#using data type as function
var=np.array([1,2,3,4])
new=np.float32(var)
print(var.dtype)
print(new.dtype)
new1=np.int64(new)
print(new1.dtype)
print(new1)

int32
float32
int64
[1 2 3 4]


In [ ]:
#Arithemtic Operation
a=np.array([1,2,3,4])
a1=a+2
print(a1)
a-2

[3 4 5 6]


array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
print("Add", a+b)
print("sub",a-b)

Add [5 5 5 5]
sub [-3 -1  1  3]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
c=np.multiply(a,b)
print(c)
c=np.divide(a,b)
print(c)


[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]


In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4]])
a1=a+2
print(a1)

[[3 4 5 6]
 [3 4 5 6]]


In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4]])
a1=np.array([[11,12,13,14],[21,22,23,24]])
a2=a+a1
print(a2)

[[12 14 16 18]
 [22 24 26 28]]


In [ ]:
#Arithmetic Functions
a=np.array([1,2,3,4])
print("min: ",np.min(a))
print("max: ",np.max(a))

min:  1
max:  4


In [ ]:
a=np.array([1,2,3,4])
print("min: ",np.min(a),np.argmin(a))   #Returns the indices of the minimum values along an axis
print("max: ",np.max(a),np.argmax(a))

min:  1 0
max:  4 3


In [ ]:
a1=np.array([[11,12,13,14],[21,22,11,24]])
print("min: ",np.min(a1),np.argmin(a1))
print("max: ",np.max(a1),np.argmax(a1))

min:  11 0
max:  24 7


In [ ]:
#axis 0= cols, axis 1= rows
a1=np.array([[[0,12,13,14],[21,22,11,24]],[[1,2,14,20],[25,26,11,2]]])
print(a1)
print()
print("min: ",np.min(a1,axis=0))
print()
print("max: ",np.max(a1,axis=1))
print("min: ",np.min(a1,axis=2))

[[[ 0 12 13 14]
  [21 22 11 24]]

 [[ 1  2 14 20]
  [25 26 11  2]]]

min:  [[ 0  2 13 14]
 [21 22 11  2]]

max:  [[21 22 13 24]
 [25 26 14 20]]
min:  [[ 0 11]
 [ 1  2]]


In [ ]:
#axis 0= cols, axis 1= rows
a1=np.array([[[40,12,13,14],[21,22,11,24],[25,26,11,2]]])
print(a1)
print()
print("min: ",np.min(a1,axis=0))
print()
print("max: ",np.max(a1,axis=1))
print("min: ",np.min(a1,axis=2))

[[[40 12 13 14]
  [21 22 11 24]
  [25 26 11  2]]]

min:  [[40 12 13 14]
 [21 22 11 24]
 [25 26 11  2]]

max:  [[40 26 13 24]]
min:  [[12 11  2]]


In [ ]:
a1=np.array([[11,12,13,14],[21,22,11,24]])
print("min: ",np.min(a1,axis=0),np.argmin(a1, axis=0))
print("max: ",np.max(a1,axis=1),np.argmax(a1, axis=1))

min:  [11 12 11 14] [0 0 1 0]
max:  [14 24] [3 3]


In [ ]:
a1=np.array([[4,12,13,16],[25,22,11,24]])
print("Square root: ",np.sqrt(a1))

Square root:  [[2.         3.46410162 3.60555128 4.        ]
 [5.         4.69041576 3.31662479 4.89897949]]


In [ ]:
a1=np.array([[11,12,13,14],[21,22,11,24]])
print("Sin: ",np.sin(a1))

Sin:  [[-0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.83665564 -0.00885131 -0.99999021 -0.90557836]]


In [ ]:
a1=np.array([[11,12,13,14],[21,22,11,24]])
print("Cos: ",np.cos(a1))

Cos:  [[ 0.0044257   0.84385396  0.90744678  0.13673722]
 [-0.54772926 -0.99996083  0.0044257   0.42417901]]


In [ ]:
a=np.array([1,2,3,4])
print("Cumulative Sum", np.cumsum(a))

Cumulative Sum [ 1  3  6 10]


In [ ]:
a1=np.array([[11,12,13,14],[21,22,11,24]])
print("Cumulative Sum", np.cumsum(a1))

Cumulative Sum [ 11  23  36  50  71  93 104 128]


**Linear Algebra**

In [ ]:
#Matrix multiplication
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#Calculating the determinant of a matrix
c=np.identity(3)
print(c)
np.linalg.det(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
#Calculating the determinant of a matrix
c=np.array([[1,2,3],[3,2,1],[2,1,3]])
print(c)
np.linalg.det(c)


[[1 2 3]
 [3 2 1]
 [2 1 3]]


-12.000000000000005

In [ ]:
#Compute the eigenvalues of a general matrix
np.linalg.eigvals(c)



array([ 6.        , -1.41421356,  1.41421356])

**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.max(stats)

6

In [ ]:
#0=column, 1=row(3,6)
np.max(stats, axis=0)


array([4, 5, 6])

In [ ]:
np.sum(stats, axis=1)


array([ 6, 15])

In [ ]:
# 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(array_3d)
print()
# Sum over axis 0
sum_axis0 = np.sum(array_3d, axis=0)
print(sum_axis0)
print()
# Sum over axis 1
sum_axis1 = np.sum(array_3d, axis=1)
print(sum_axis1)
print()
# Sum over axis 2
sum_axis2 = np.sum(array_3d, axis=2)
print(sum_axis2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[12 15 18]]

[[ 6 15 24]]


In [ ]:
# 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[0,0,0]]])
print(array_3d,"\n")

# Sum over axis 0
sum_axis0 = np.sum(array_3d, axis=0)
print("sum",sum_axis0)
print()
# Sum over axis 1
sum_axis1 = np.sum(array_3d, axis=1)
print(sum_axis1)
print()
# Sum over axis 2
sum_axis2 = np.sum(array_3d, axis=2)
print(sum_axis2)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 0 0]]] 

sum [[ 8 10 12]
 [ 4  5  6]]

[[5 7 9]
 [7 8 9]]

[[ 6 15]
 [24  0]]


**Shape &** **Reshape**

In [ ]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var,"\n")
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]] 

(2, 4)


In [ ]:
var=np.array([1,2,3,4],ndmin=4)
print(var,"\n")
print(var.shape)

[[[[1 2 3 4]]]] 

(1, 1, 1, 4)


In [ ]:
var=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var,"\n")
x=var.reshape(2,6)
print(x,"\n")
x=var.reshape(2,3,2)
print(x,"\n")
var1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
x=var1.reshape(18,1)
print(x)

var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
x=var2.reshape(2,2,2,2)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]]
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [ ]:
print(x,"\n")
print("onedim",x.reshape(-1))




[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]] 

onedim [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
v1 = np.array([[1,2,3],[4,5,6]])
v2 = np.array([[5,6],[7,8]])
np.hstack([v1,v2])

array([[1, 2, 3, 5, 6],
       [4, 5, 6, 7, 8]])

**Indexing and Slicing**

In [ ]:
y1=np.array([1,2,3])
print(y1[1])
print(y1[-2])

2
2


In [ ]:
y1=np.array([[1,2,3],[4,5,6]])
#Get a specific element [r,c],python indexing starts from 0
y1[1,1]


5

In [ ]:
a5=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a5)
#Get a specific element [r,c],python indexing starts from 0
a5[0,3]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


4

In [ ]:
a6=np.array([[[1,2,3],[4,5,6]]])
print(a6[0,1,1])

5


In [ ]:
#Slicing start:stop:step
#Get a specific row
a5[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a5[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
var=np.array([1,2,3,4,5])
print(var[:7])

print(var[:4])


[1 2 3 4 5]
[1 2 3 4]


In [ ]:
print(var[::2])

[1 3 5]


In [ ]:
print(var[2::2])

[3 5]


In [ ]:
a7=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a7[0,2,2])

9


**Iterating Numpy Arrays**

In [ ]:
var=np.array([1,2,3,4,5,6,7])
print(var,"\n")

for i in var:
  print(i)

[1 2 3 4 5 6 7] 

1
2
3
4
5
6
7


In [ ]:
var=np.array([[1,2,3,4],[8,9,10,11]])
print(var,"\n")

for i in var:
  print(i)

[[ 1  2  3  4]
 [ 8  9 10 11]] 

[1 2 3 4]
[ 8  9 10 11]


In [ ]:
var=np.array([[1,2,3,4],[8,9,10,11]])
print(var,"\n")

for i in var:
  for k in i:
    print(k)

[[ 1  2  3  4]
 [ 8  9 10 11]] 

1
2
3
4
8
9
10
11


In [ ]:
var=np.array([[[1,2,3,4],[8,9,10,11]]])
print(var,"\n")

for i in var:
  for k in i:
    for j in k:
      print(j)

[[[ 1  2  3  4]
  [ 8  9 10 11]]] 

1
2
3
4
8
9
10
11


In [ ]:
var=np.array([[[1,2,3,4],[8,9,10,11]]])
print(var,"\n")

for i in np.nditer(var):
  print(i)

[[[ 1  2  3  4]
  [ 8  9 10 11]]] 

1
2
3
4
8
9
10
11


In [ ]:
var=np.array([[[1,2,3,4],[8,9,10,11]]])
print(var,"\n")

for i,d in np.ndenumerate(var):
  print(i,d)

[[[ 1  2  3  4]
  [ 8  9 10 11]]] 

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 8
(0, 1, 1) 9
(0, 1, 2) 10
(0, 1, 3) 11


In [ ]:
var=np.array([[1,2,3,4],[8,9,10,11]])
print(var,"\n")

for i,d in np.ndenumerate(var):
  print(i,d)

[[ 1  2  3  4]
 [ 8  9 10 11]] 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 8
(1, 1) 9
(1, 2) 10
(1, 3) 11


**Copy & View**

In [ ]:
var=np.array([1,2,3,4,5,6,7])
print(var,"\n")
co=var.copy()
print(co,"\n")

[1 2 3 4 5 6 7] 

[1 2 3 4 5 6 7] 



In [ ]:
var=np.array([1,2,3,4,5,6,7])
print(var,"\n")
vi=var.view()
print(vi,"\n")

[1 2 3 4 5 6 7] 

[1 2 3 4 5 6 7] 



In [ ]:
var=np.array([1,2,3,4,5,6,7])
co=var.copy()
var[1]=40
print(var,"\n")
print(co,"\n")

[ 1 40  3  4  5  6  7] 

[1 2 3 4 5 6 7] 



In [ ]:
var=np.array([1,2,3,4,5,6,7])
vi=var.view()
var[1]=40
print(var,"\n")
print(vi,"\n")

[ 1 40  3  4  5  6  7] 

[ 1 40  3  4  5  6  7] 



In [ ]:
var=np.array([1,2,3,4,5,6,7])
co=var.copy()
co[2]=30
print(var,"\n")
print(co,"\n")

[1 2 3 4 5 6 7] 

[ 1  2 30  4  5  6  7] 



In [ ]:
var=np.array([1,2,3,4,5,6,7])
vi=var.view()
vi[2]=40
print(var,"\n")
print(vi,"\n")

[ 1  2 40  4  5  6  7] 

[ 1  2 40  4  5  6  7] 



**Join & Split Functions**

In [ ]:
var=np.array([1,2,3,4,5,6,7])
var1=np.array([11,12,13,14,15,16,17])

ar=np.concatenate((var,var1))
print(ar)

[ 1  2  3  4  5  6  7 11 12 13 14 15 16 17]


In [ ]:
var=np.array([[1,2],[3,4],[5,6]])
var1=np.array([[11,12],[13,14],[15,16]])
ar=np.concatenate((var,var1))
print(ar)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
var=np.array([[1,2],[3,4],[5,6]])
var1=np.array([[11,12],[13,14],[15,16]])
ar=np.concatenate((var,var1),axis=0)
print(ar)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
var=np.array([[1,2],[3,4],[5,6]])
var1=np.array([[11,12],[13,14],[15,16]])
ar=np.concatenate((var,var1),axis=1)
print(ar)

[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]]


In [ ]:
var=np.array([[[1,2],[3,4],[5,6]]])
var1=np.array([[[11,12],[13,14],[15,16]]])
ar=np.concatenate((var,var1),axis=0)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 12]
  [13 14]
  [15 16]]]


In [ ]:
var=np.array([[[1,2],[3,4],[5,6]]])
var1=np.array([[[11,12],[13,14],[15,16]]])
ar=np.concatenate((var,var1),axis=1)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
var=np.array([[[1,2],[3,4],[5,6]]])
var1=np.array([[[11,12],[13,14],[15,16]]])
ar=np.concatenate((var,var1),axis=2)
print(ar)

[[[ 1  2 11 12]
  [ 3  4 13 14]
  [ 5  6 15 16]]]


In [ ]:
var=np.array([1,2,3,4,5,6,7])
print(var)
print()
ar=np.array_split(var,3)
print(ar)

[1 2 3 4 5 6 7]

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
var=np.array([[1,2],[3,4],[5,6],[1,1]])
print(var)
print()
ar=np.array_split(var,3)
print(ar)

[[1 2]
 [3 4]
 [5 6]
 [1 1]]

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[1, 1]])]


**Search**

In [ ]:
var=np.array([1,2,3,4,5,6,7,2,8,2])
x=np.where(var==2)
print(x)

(array([1, 7, 9], dtype=int64),)


In [ ]:
var=np.array([1,2,3,4,5,6,7,2,8,2])
x=np.where(var/2==4)
print(x)

(array([8], dtype=int64),)


In [ ]:
var=np.array([1,2,3,4,5,6,7,2,8,2])
x=np.sort(var)
print(x)

[1 2 2 2 3 4 5 6 7 8]


In [ ]:
var=np.array(["a","z","c"])
x=np.sort(var)
print(x)

['a' 'c' 'z']


In [ ]:
var=np.array(["a","z","c"])
x=np.sort(var)[::-1]
print(x)

['z' 'c' 'a']


In [ ]:
arr = np.array([[3, 2, 4],
                [5, 0, 1],
                [1, 9, 7]])

arr = np.sort(arr, axis=0)
print(arr)

[[1 0 1]
 [3 2 4]
 [5 9 7]]


In [ ]:
arr = np.array([[3, 2, 4],
                [5, 0, 1],
                [1, 9, 7]])

arr = np.sort(arr, axis=1)[::-1]
print(arr)

[[1 7 9]
 [0 1 5]
 [2 3 4]]


In [ ]:
#filter array
var=np.array([1,2,3,4])
f=[True,False,True,False]
new_a=var[f]
print(new_a)

var1=np.array(["a","w","e","r"])
new_a1=var1[f]
print(new_a1)

[1 3]
['a' 'e']


**Insert**

In [ ]:
var=np.array([11,12,13,14])
print(var,"\n")
v=np.insert(var, 3, 20)
print(v)
v=np.insert(var, (2,3), [20.5,30.5])  #doesn't take float values
print(v)

[11 12 13 14] 

[11 12 13 20 14]
[11 12 20 13 30 14]


In [ ]:
var=np.array([[1,2,3],[4,5,6]])
print(var,"\n")
v=np.insert(var, (6), 20)
print(v,"\n")
v=np.insert(var, (2), 20,axis=0)
print(v,"\n")
v=np.insert(var, (2,3), 20.5,axis=1)  #doesn't take float values
print(v,"\n")
v=np.insert(var, 1, [7,8],axis=1)
print(v,"\n")

[[1 2 3]
 [4 5 6]] 

[ 1  2  3  4  5  6 20] 

[[ 1  2  3]
 [ 4  5  6]
 [20 20 20]] 

[[ 1  2 20  3 20]
 [ 4  5 20  6 20]] 

[[1 7 2 3]
 [4 8 5 6]] 



In [ ]:
var=np.array([11,12,13,14])
print(var,"\n")
v=np.append(20,var)  #append at the start
print(v)

[11 12 13 14] 

[20 11 12 13 14]


In [ ]:
var=np.array([11,12,13,14])
print(var,"\n")
v=np.append(var, 20) #append at the end
print(v)

[11 12 13 14] 

[11 12 13 14 20]


In [ ]:
var=np.array([[1,2,3],[4,5,6]])
var1=np.append(var,[[7,8,9]],axis=0)
print(var1,"\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [ ]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
var1=np.append(var,[[7],[8]],axis=1)
print(var1,"\n")

[[1 2 3]
 [4 5 6]]
[[1 2 3 7]
 [4 5 6 8]] 



**Delete**

In [ ]:
var=np.array([11,12,13,14])
print(var,"\n")
v=np.delete(var, 2)
print(v)

[11 12 13 14] 

[11 12 14]


**Matrix**

In [ ]:
var=np.array([11,12,13,14])
print(var,"\n")
print(type(var),"\n")

var1=np.matrix([11,12,13,14])
print(var1,"\n")
print(type(var1),"\n")

[11 12 13 14] 

<class 'numpy.ndarray'> 

[[11 12 13 14]] 

<class 'numpy.matrix'> 



In [ ]:
#arithmetic operation in matrix

var1=np.matrix([[1,2],[3,4]])
var2=np.matrix([[1,2],[3,4]])
print(var1+var2,"\n")

print(var1*var2,"\n")
print(var1.dot(var2))
print()
print(np.matmul(var1,var2))


[[2 4]
 [6 8]] 

[[ 7 10]
 [15 22]] 

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]


In [ ]:
var1 @ var2

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
var1=np.matrix([[1,2],[3,4]])
print(np.transpose(var1))
print(var1.T)

var11=np.array([[1,2,3],[3,4,1]])
print(np.transpose(var11))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]
 [3 1]]


In [ ]:
var1=np.matrix([[1,22],[3,1]])
print(var1)
print(np.linalg.matrix_power(var1,2))


var11=np.array([[1,2],[3,4]])
print(np.linalg.matrix_power(var11,2))

[[ 1 22]
 [ 3  1]]
[[67 44]
 [ 6 67]]
[[ 7 10]
 [15 22]]


In [ ]:
var11=np.array([[1,2,3],[3,4,1]])
var12=np.array([[1,2,3],[3,4,1]])
print(var11*var12,"\n")

[[ 1  4  9]
 [ 9 16  1]] 



In [ ]:
arr1=list(range(1000000))
arr2=list(range(1000000,2000000))

arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [ ]:
%%time
result=0
for x1,x2 in zip(arr1,arr2):
  result+=x1*x2
result


CPU times: total: 156 ms
Wall time: 306 ms


833332333333500000

In [ ]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 1.02 ms


-1942957984

In [ ]:
#Create an identity matrix of dimension 4-by-4
i = np.eye(4)

print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Convert a binary numpy 2D array (containing only 0s and 1s) to a boolean numpy array
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

o = a.astype('bool')
a1 = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]],dtype='bool')
print(o)
print()
print(a1)

[[ True False False]
 [ True  True  True]
 [False False False]]

[[ True False False]
 [ True  True  True]
 [False False False]]


In [ ]:
#Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....
o = np.arange(0, 101, 2)

print(o)

list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
#Getting the positions (indexes) where elements of 2 numpy arrays match
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a != b))

print(np.where(a == b))

(array([1, 2], dtype=int64),)
(array([0, 3, 4], dtype=int64),)


In [ ]:
#Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)
o = np.random.randint(0, 10, size = (5,5))

print(o)

[[5 2 7 1 2]
 [7 0 3 1 3]
 [4 9 5 5 9]
 [6 3 5 1 5]
 [4 9 7 9 2]]


In [ ]:
#Output the transpose of a matrix
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a_transpose = a.T

print(a_transpose)
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
#Check whether a Numpy array contains a specified row
import numpy

# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])

# view array
print(arr)

# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [ ]:
# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, np.nan, 3.8],
                  [41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr)])
print()
print(n_arr[np.isnan(n_arr)])

Given array:
[[10.5  nan  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[10.5  3.8 41. ]

[nan nan nan]


In [ ]:
#Create a filter array that will return only values higher than 42
import numpy as np
arr = np.array([41, 42, 43, 44,50,-50])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True, True, False]
[43 44 50]
